CREATE TABLE `accidentreports`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` double NULL, `DateTimeOfAccident` datetime NULL, `DateOfReport` datetime NULL, `WhoHadAccident` mediumtext NULL, `WhoReportedIt` varchar(75) NULL, `ReportDetailFiles` mediumtext NULL, `ReportDetails` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, `SentReceived` varchar(75) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `asbestosreports`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NOT NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SentReceived` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedOn` datetime NULL, `LastEditedBy` varchar(30) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `benchmarksanddatasheets`(`ID` int NOT NULL AUTO_INCREMENT, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `Status` varchar(30) NULL, `FlatNo` varchar(20) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `brochures`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `BrochureUpdateDate` datetime NULL, `SentReceived` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `buildingcontrol`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `buildingleaseconsent`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `clientcorrespondence`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SentOrReceived` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditeOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `clientrequestsandinstructions`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `companystructure`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `contracts`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `costplan`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `CommentBox` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `dayworksheets`(`ID` int NOT NULL AUTO_INCREMENT, `UserID` int NOT NULL, `JobID` int NOT NULL, `SubmittedChangedApproved` varchar(50) NULL, `WeekEndingDateWorked` date NULL, `Type` varchar(75) NULL, `WorksheetTemplate` varchar(75) NULL, `DayWorksheetsFile` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `documenttemplates`(`ID` int NOT NULL AUTO_INCREMENT, `WindowName` varchar(75) NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `File` mediumtext NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `doorandironmongery`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `drawings`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Files` mediumtext NULL, `CommentBox` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `environmentalcossh`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `finalaccounts`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `CommentBox` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `finalcontracts`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `floorfinishesschedule`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `furniture`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `handoverandcompletioncertificates`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `DateReceived` datetime NULL, `SentOrReceived` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditeOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `healthandsafetyaudits`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedOrComplete` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `healthandsafetyinspectionreports`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` int NULL, `Files` mediumtext NULL, `SubmittedChangedOrComplete` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `healthandsafetyphaseplan`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `incomingtenders`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `invoicing`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `CommentBox` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `job`(`ID` int NOT NULL AUTO_INCREMENT, `ProjectName/No` varchar(50) NULL, `ProjectName` varchar(30) NOT NULL, `ProjectNo` varchar(30) NOT NULL, `StaffInvolved` mediumtext NULL, `Contractors` mediumtext NULL, `StartDate` datetime NULL, `Program` mediumtext NULL, `F10` mediumtext NULL, `CompanyInsurance` mediumtext NULL, `LastEditedOn` datetime NULL, `LastEditedBy` varchar(30) NULL, `JobStatus` varchar(30) NULL, `FinishDate` datetime NULL, `DilapidationReport` mediumtext NULL, `SiteManagerCertificateSMSTS` mediumtext NULL, `SiteManagerCertificateFirstAid` mediumtext NULL, `SiteManagerCertificateCSCS` mediumtext NULL, `SiteRules` mediumtext NULL, `SiteLogisticsPlan` mediumtext NULL, `MeterReadings` mediumtext NULL, `CompanyInsuranceExpiry` datetime NULL, `F10Expiry` datetime NULL, `SiteManagerCertificateSMSTSExpiry` datetime NULL, `SiteManagerCertificateFirstAidExpiry` datetime NULL, `SiteManagerCertificateCSCSExpiry` datetime NULL, `ConstructionPhasePlanTemplate` varchar(75) NULL, `ConstructionPhasePlanFiles` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `Address` mediumtext NULL, `Postcode` varchar(50) NULL, `Country` varchar(50) NULL, `GoodsLiftDimentions` mediumtext NULL, `DeliveryProcedure` mediumtext NULL, `SiteRulesTemplate` varchar(75) NULL, `DilapidationReportTemplate` varchar(75) NULL, `MeterReadingsTemplate` varchar(75) NULL, `GoodsLiftDimensionsTemplate` varchar(75) NULL, `DeliveryProcedureTemplate` varchar(75) NULL, `Lat` decimal(20,10) NULL, `Lng` decimal(20,10) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `keyhregister`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `letterofintent`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `lookup`(`Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Value` varchar(75) NULL)CHARACTER SET utf8;
CREATE TABLE `meetingminutes`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `DateHeld` datetime NULL, `ChairedBy` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `SentOrReceived` varchar(75) NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `news`(`ID` int NOT NULL AUTO_INCREMENT, `NewsInfo` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `orderform`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `outgoingtenders`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `ownersmanual`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `ReceivedComplete` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `peopletimesheet`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NOT NULL, `UserID` int NOT NULL, `WeekEndingDateWorked` date NULL, `Type` varchar(75) NULL, `TimesheetTemplate` varchar(75) NULL, `PeopleTimesheetFile` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `permit`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `MobileNumber` varchar(50) NULL, `IssueDate` date NULL, `IssueTime` time NULL, `ExpiryDate` date NULL, `ExpiryTime` time NULL, `SubmittedCancelled` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `precontracts`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `procurement`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `CommentBox` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `progressreports`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `purchaseorders`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `quotationinstructions`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `rams`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `ReviewFormTemplate` int NULL, `RAMS` mediumtext NULL, `RAMSTemplate` int NULL, `CompanyLiabilityInsuranceDocument` mediumtext NULL, `CompanyLiabilityInsuranceExpiresOn` datetime NULL, `DateSubmited` date NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `rfis`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `rubbishremoval`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedComplete` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `samplesandvisuals`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `secretarial`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `Status` varchar(500) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditeOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `signinregister`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `sirtet_uggroups`(`GroupID` int NOT NULL AUTO_INCREMENT, `Label` varchar(300) NULL, PRIMARY KEY (`GroupID`))CHARACTER SET utf8;
CREATE TABLE `sirtet_ugmembers`(`UserName` varchar(300) NOT NULL, `GroupID` int NOT NULL, PRIMARY KEY (`UserName`(50),`GroupID`))CHARACTER SET utf8;
CREATE TABLE `sirtet_ugrights`(`TableName` varchar(300) NOT NULL, `GroupID` int NOT NULL, `AccessMask` varchar(10) NULL, PRIMARY KEY (`TableName`(50),`GroupID`))CHARACTER SET utf8;
CREATE TABLE `sitedeliverybookings`(`id` int NOT NULL AUTO_INCREMENT, `JobID` int NOT NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `AddedBy` varchar(100) NULL, `DriverName` varchar(50) NULL, `DriverSurname` varchar(50) NULL, `VehicleType` varchar(50) NULL, `VehicleMake` varchar(50) NULL, `VehicleRegistrationNumber` varchar(50) NULL, `DriverMobileNumber` varchar(50) NULL, `DateOfDelivery` date NULL, `TimeOfDelivery` time NULL, `DeliveryDescription` mediumtext NULL, `FromPostCode` varchar(50) NULL, `BookedOrCancelled` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(75) NULL, `LastEditedOn` datetime NULL, `PickupDropoff` varchar(50) NULL, `GoogleMapRoute` varchar(1000) NULL, `ToPostCode` varchar(1000) NULL, PRIMARY KEY (`id`))CHARACTER SET utf8;
CREATE TABLE `siteinduction`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NOT NULL, `Files` mediumtext NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `CertificateSMSTS` mediumtext NULL, `CertificateSMSTSExpiry` datetime NULL, `CertificateFirstAid` mediumtext NULL, `CertificateFirstAidExpiry` datetime NULL, `CertificateCSCS` mediumtext NULL, `CertificateCSCSExpiry` datetime NULL, `PersonNameAndSurname` varchar(75) NULL, `DateOfInduction` datetime NULL, `InductedNotInducted` varchar(50) NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `siteinstructionsandvariations`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Files` mediumtext NULL, `Template` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `SubmittedChangedComplete` varchar(75) NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `siteprogressphotos`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `sitesetup`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Files` mediumtext NULL, `Template` varchar(75) NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `DateSubmited` date NULL, `PlannedRemovalDate` date NULL, `ActualRemovalDate` date NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `ska`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `skillscertificates`(`ID` int NOT NULL AUTO_INCREMENT, `Type` mediumtext NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `ExpiryDate` datetime NULL, `WorkerType` varchar(75) NULL, `WorkerName` varchar(75) NULL, `CompanyName` varchar(75) NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `snagging`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `UpdateAndComplete` varchar(50) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedOn` datetime NULL, `LastEditedBy` varchar(30) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `specifications`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SubmittedChangedApproved` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `survey`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `SubType` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `DateDone` datetime NULL, `SubmittedUpdatedComplete` varchar(75) NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `timelaps`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedBy` varchar(30) NULL, `LastEditedOn` datetime NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `toolboxtalks`(`ID` int NOT NULL AUTO_INCREMENT, `JobID` int NULL, `Type` varchar(75) NULL, `Template` varchar(75) NULL, `Files` mediumtext NULL, `DateImplemented` date NULL, `SendEmailTo` mediumtext NULL, `EmailNote` mediumtext NULL, `LastEditedOn` datetime NULL, `LastEditedBy` varchar(30) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `users`(`ID` int NOT NULL AUTO_INCREMENT, `username` varchar(300) NULL, `password` varchar(300) NULL, `email` varchar(300) NULL, `fullname` varchar(300) NULL, `active` int NULL, `FirstName` varchar(75) NULL, `Surname` varchar(75) NULL, `Company` varchar(75) NULL, `Roles` mediumtext NULL, `Type` varchar(50) NULL, `Status` varchar(50) NULL, `Barcode` mediumtext NULL, `LastEditedOn` datetime NULL, `LoginCount` int NULL DEFAULT 0, `JobID` int NULL, `LastEditedBy` varchar(30) NULL, `DefaultCompanyContact` int NULL DEFAULT 0, `MobileNumber` varchar(50) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (304,'RAMS Review Form','Sirtet','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (305,'RAMS Template','AV','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (336,'Permit','Comms Room','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (349,'Site Induction','Site Operatives','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (351,'Sign In Register','Security Sign In Register','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (352,'Asbestos Report','Landlords Asbestos Report','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (354,'Toolbox Talks','Default','','info.txt');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (355,'Site Instructions And Variations','Default','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (356,'Requests And Instructions','Site Request For Information','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (358,'Client Correspondence','Default','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (361,'H&S Audits','H&S Consultant Audit','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (363,'H&SPP','H&SPP','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (364,'Construction Phase Plan','Construction Phase Plan Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (365,'Meeting Minutes','Consultant Pre Contracts Meeting','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (380,'Purchase Orders','Contractor Change Order','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (386,'Progress Reports','Consultants Progress Reports','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (406,'H&S Inspection Reports','Weekly Site Managers Health & Safety Inspection','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (407,'Specifications','Specifications','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (408,'RFIs','RFIs','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (409,'Owners Manual','Sprinklers','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (410,'Building Control','Building Control','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (411,'Environmental And COSSH','Environmental Policy','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (414,'Drawings','Drawings','Draw1','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (417,'People Time Sheet','Sample People Time Sheet','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (418,'Site Progress Photos','Site Progress Photos Default Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (419,'Survey','Survey','1','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (420,'Timelaps','Default','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (421,'Key H Register','Key H Register Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (422,'Site Setup','Site Setup Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (423,'Rubbish Removal','Rubbish Removal Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (424,'Snagging','Snagging Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (425,'SKA','SKA Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (426,'Brochures','Comp1','Prod1','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (427,'Furniture','Furniture Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (428,'Samples and Visuals','Samples and Visuals Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (429,'Door and Ironmongery','Door and Ironmongery Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (430,'Floor Finishes Schedule','Floor Finishes Schedule Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (431,'Pre Contracts','Pre Contracts Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (432,'Final Contracts','Final Contracts Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (433,'Contracts','Contracts Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (434,'Company Structure','Company Structure Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (435,'Quotation Instructions','Quotation Instructions Template','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (436,'Skills Certificates','ECS','','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (446,'Benchmarks And Datasheets','AV','AV - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (447,'Benchmarks And Datasheets','AV','AV - Template2','api_interface.php');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (448,'Benchmarks And Datasheets','Blinds','Blinds - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (449,'Benchmarks And Datasheets','BT','BT - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (450,'Benchmarks And Datasheets','Carpet','Carpet - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (451,'Benchmarks And Datasheets','Ceilings ','Ceilings  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (452,'Benchmarks And Datasheets','Construction ','Construction  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (453,'Benchmarks And Datasheets','Crane lifting','Crane lifting - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (454,'Benchmarks And Datasheets','Data','Data - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (455,'Benchmarks And Datasheets','Decorating','Decorating - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (456,'Benchmarks And Datasheets','Demolition','Demolition - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (457,'Benchmarks And Datasheets','Electrical','Electrical - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (458,'Benchmarks And Datasheets','Fabricks','Fabricks - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (459,'Benchmarks And Datasheets','Fire Alarms','Fire Alarms - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (460,'Benchmarks And Datasheets','Flooring ','Flooring  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (461,'Benchmarks And Datasheets','Furniture','Furniture - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (462,'Benchmarks And Datasheets','Gas Supresion','Gas Supresion - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (463,'Benchmarks And Datasheets','Glazing Parition','Glazing Parition - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (464,'Benchmarks And Datasheets','Ground Works','Ground Works - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (465,'Benchmarks And Datasheets','Hand Rails ','Hand Rails  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (466,'Benchmarks And Datasheets','Joinery ','Joinery  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (467,'Benchmarks And Datasheets','Lifts','Lifts - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (468,'Benchmarks And Datasheets','Manifestation','Manifestation - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (469,'Benchmarks And Datasheets','Mechanical ','Mechanical  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (470,'Benchmarks And Datasheets','Partitioning','Partitioning - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (471,'Benchmarks And Datasheets','Pile Caping ','Pile Caping  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (472,'Benchmarks And Datasheets','Plumbing','Plumbing - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (473,'Benchmarks And Datasheets','Quooker','Quooker - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (474,'Benchmarks And Datasheets','Security ','Security  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (475,'Benchmarks And Datasheets','Splach Backs ','Splach Backs  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (476,'Benchmarks And Datasheets','Stairs','Stairs - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (477,'Benchmarks And Datasheets','Tiling','Tiling - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (478,'Benchmarks And Datasheets','Vivreau Taps ','Vivreau Taps  - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (479,'Benchmarks And Datasheets','Zip Taps','Zip Taps - Template','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (480,'Building Lease Consent','Default','NA','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (481,'Letter Of Intent','Letter Of Intent Type',NULL,NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (482,'Incoming Tenders','Incoming Type 1','Sub Type 1','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (483,'Outgoing Tenders','Default','Def1',NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (484,'Incoming Tenders','Incoming Type 1','Sub Type 2','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (485,'Incoming Tenders','123','123','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (486,'Survey','Survey','2','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (487,'Survey','Survey 2','3','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (488,'Drawings','Drawings','Draw2','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (489,'Drawings','Drawings','Draw3','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (490,'Survey','surv1','surv01','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (491,'Survey','surv1','NA','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (493,'Survey','surv2','surv01','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (494,'Handover And Completion Certificates','Handover And Completion Certificates 1',NULL,NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (495,'Outgoing Tenders','Default','Def2','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (496,'Outgoing Tenders','Def1','Def1','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (497,'Brochures','Comp2','Prod1','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (499,'Brochures','Comp1','Prod2','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (500,'Order Form','Order Form Type 1',NULL,NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (501,'Owners Manual','Lawmans','Demolition ','');
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (502,'Secretarial','Sec1','123',NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (503,'Procurement','Procurement 1','123',NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (504,'Final Accounts','Final Accounts 1','123',NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (506,'Cost Plan','Cost Plan 1','123',NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (507,'Site Delivery Bookings','Site Delivery Bookings Type 1',NULL,NULL);
INSERT INTO `documenttemplates` (`ID`,`WindowName`,`Type`,`SubType`,`File`) VALUES (508,'Site Delivery Bookings','Site Delivery Bookings Type 2',NULL,NULL);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Job Status','','Open');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Job Status','','Closed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Staff','Employed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Staff','Not Employed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Contractor','Appointed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Contractor','Not Appointed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Project Manager');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Construction Manager');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Health And Safety Manager');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Site Manager');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Contract Manager');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Designer');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Office Admin');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('WorkType','','Administer');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('WorkType','','Labor');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('MeetingType','','Client');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('MeetingType','','Consultant');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('MeetingType','','Sub Contractor');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Specification Type','','Broad Spec');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Specification Type','','Detailed Spec');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('SentOrReceived','','Received');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('SentOrReceived','','Sent');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Correspondence Type','','Fax');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Correspondence Type','','Email');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Correspondence Type','','Post');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Type','','Contractor');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Type','','Site Based Staff');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Type','','Staff');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Type','','Consultant');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Sign In Register','','Site Sign In Register');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Sign In Register','','Security Sign In Register');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Operative');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('SubmitedChangedApproved','','Submited Or Changed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('SubmitedChangedApproved','','Approved');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Send Mail','','Dont Send');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Send Mail','','Send');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Consultant','Appointed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Consultant','Not Appointed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Director');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Sales');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','IT');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('Roles','','Quantity Surveyor');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('UpdateAndComplete','','Update');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('UpdateAndComplete','','Complete');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Site Based Staff','Employed');
INSERT INTO `lookup` (`Type`,`SubType`,`Value`) VALUES ('User Status','Site Based Staff','Not Employed');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `sirtet_ugmembers` (`UserName`,`GroupID`) VALUES ('admin',-1);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('accidentreports',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('asbestosreports',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('benchmarksanddatasheets',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('brochures',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('buildingcontrol',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('buildingleaseconsent',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('clientcorrespondence',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('clientrequestsandinstructions',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('companystructure',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('contracts',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('costplan',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('dayworksheets',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('directory',-1,'ESP');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('documenttemplates',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('doorandironmongery',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('drawings',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('environmentalcossh',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('finalaccounts',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('finalcontracts',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('floorfinishesschedule',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('furniture',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('handoverandcompletioncertificates',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('healthandsafetyaudits',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('healthandsafetyinspectionreports',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('healthandsafetyphaseplan',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('incomingtenders',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('invoicing',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('job',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('keyhregister',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('letterofintent',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('lookup',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('meetingminutes',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('news',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('orderform',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('outgoingtenders',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('ownersmanual',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('peopletimesheet',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('permit',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('precontracts',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('procurement',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('progressreports',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('purchaseorders',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('quotationinstructions',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('rams',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('rfis',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('rubbishremoval',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('samplesandvisuals',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('secretarial',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('signinregister',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('sitedeliverybookings',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('siteinduction',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('siteinstructionsandvariations',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('siteprogressphotos',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('sitesetup',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('ska',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('skillscertificates',-1,'ADESPI');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('snagging',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('specifications',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('survey',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('timelaps',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('toolboxtalks',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('users',-1,'ADESPIM');
INSERT INTO `sirtet_ugrights` (`TableName`,`GroupID`,`AccessMask`) VALUES ('users_emailList',-1,'ASPIM');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `users` (`ID`,`username`,`password`,`email`,`fullname`,`active`,`FirstName`,`Surname`,`Company`,`Roles`,`Type`,`Status`,`Barcode`,`LastEditedOn`,`LoginCount`,`JobID`,`LastEditedBy`,`DefaultCompanyContact`,`MobileNumber`) VALUES (1,'admin','admin',NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,0,NULL);
SET FOREIGN_KEY_CHECKS = 1;
